PetShop/force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PetShop/force-app/main/default/objects/Pet__c/fields/Especie__c.field-meta.xml
<CustomField>
    <fullName>Especie__c</fullName>
    <label>Espécie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cachorro</fullName>
            </value>
            <value>
                <fullName>Gato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PetShop/force-app/main/default/objects/Pet__c/fields/Raca__c.field-meta.xml
<CustomField>
    <fullName>Raca__c</fullName>
    <label>Raça</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Especie__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vira-lata</fullName>
            </value>
            <value>
                <fullName>Poodle</fullName>
            </value>
            <value>
                <fullName>Siamês</fullName>
            </value>
            <value>
                <fullName>Persa</fullName>
            </value>
            <value>
                <fullName>Pastor-alemão</fullName>
            </value>
            <value>
                <fullName>Buldogue</fullName>
            </value>
            <value>
                <fullName>Labrador retriever</fullName>
            </value>
            <value>
                <fullName>Golden retriever</fullName>
            </value>
            <value>
                <fullName>Beagle</fullName>
            </value>
            <value>
                <fullName>Dachshund</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Husky siberiano</fullName>
            </value>
            <value>
                <fullName>Ragdoll</fullName>
            </value>
            <value>
                <fullName>Gato-de-bengala</fullName>
            </value>
            <value>
                <fullName>Scottish Fold</fullName>
            </value>
            <value>
                <fullName>Azul russo</fullName>
            </value>
            <value>
                <fullName>Gato abissíni</fullName>
            </value>
            <value>
                <fullName>Sphynx</fullName>
            </value>
            <value>
                <fullName>Siberiano</fullName>
            </value>
            <value>
                <fullName>Himalaio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PetShop/force-app/main/default/classes/CertificadoDoPetExtension.cls
public class CertificadoDoPetExtension {
    
    private Pet__c pet;

    public Boolean temFotos {get;set;}

    public CertificadoDoPetExtension(ApexPages.StandardController standardPageController) {
		pet = (Pet__c)standardPageController.getRecord();
	}

    public PageReference attachPDF() {
        pet = getPetValues(pet);
        
        PageReference pdfPage =  Page.PDFCertificado;
        pdfPage.getParameters().put('Id',pet.Id);
        Blob pdfBlob;
        if (!Test.isRunningTest()) {
            pdfBlob = pdfPage.getContent();
        } else {
            pdfBlob = Blob.valueOf('Some Text for a boring PDF file...');
        }
        
        Attachment attach = new Attachment(parentId = pet.Id, Name = 'CertificadoPet.pdf', body = pdfBlob, ContentType='application/pdf');
		insert attach;
        
        PageReference pageWhereWeWantToGo = new ApexPages.StandardController(pet).view();
        pageWhereWeWantToGo.setRedirect(true);
        return pageWhereWeWantToGo;
    }


    public PageReference loadInfo(){
        temFotos = false;
        List<ContentDocumentLink> files = PetPhotosController.getFiles(pet.Id);

        if(files.size() > 0)
            temFotos = true;
        
        return null;
    }
    
    
    private static Pet__c getPetValues(Pet__c pet){
        Pet__c result = new Pet__c();
        if(pet != null && pet.Id != null){
            result = [SELECT Id, Name, Raca__c, Especie__c FROM Pet__c WHERE Id =: pet.Id];
        }
        return result;
    }
    
}