PetShop/force-app/main/default/objects/Adocao__c/Adocao__c.object-meta.xml
<CustomObject>
    <label>Adoção</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nome de Adoção</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoções</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PetShop/force-app/main/default/objects/Adocao__c/fields/AniversarioAdocao__c.field-meta.xml
<CustomField>
    <fullName>AniversarioAdocao__c</fullName>
    <formula>AND(
Data__c != TODAY(),
AniversarioAdocaoEsteDia__c,
AniversarioAdocaoEsteMes__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aniversário de adoção?</label>
    <type>Checkbox</type>
</CustomField>

PetShop/force-app/main/default/objects/Adocao__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Adoções</relationshipLabel>
    <relationshipName>Adocoes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PetShop/force-app/main/default/objects/Adocao__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoções</relationshipLabel>
    <relationshipName>Adocoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PetShop/force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PetShop/force-app/main/default/classes/AniversarioAdocaoSchedule.cls
global class AniversarioAdocaoSchedule implements Schedulable{
    global void execute(SchedulableContext ctx) {
        List<Adocao__c> lAdocao = [SELECT Id, Data__c, Contato__c, Contato__r.OwnerId, Contato__r.Name, Pet__c, Pet__r.Name FROM Adocao__c WHERE AniversarioAdocao__c = true];
        List<Task> lTarefas = new List<Task>();

        if(lAdocao.size() > 0){
            for(Adocao__c i : lAdocao){
                Task tarefa = new Task();
                tarefa.Status = 'Não iniciado';
                tarefa.Subject = 'Aniversário de adoção';
                tarefa.Priority = 'Baixa';
                tarefa.WhatId = i.Id;
                tarefa.OwnerId = i.Contato__r.OwnerId;
                tarefa.Description = 'Envie os parabéns pelo aniversário de adoção do pet ' + i.Pet__r.Name + ' ao dono ' + i.Contato__r.Name;
                tarefa.ActivityDate = getDataVencimento();

                lTarefas.add(tarefa);
            }
        }

        if(lTarefas.size() > 0)
            insert lTarefas;
    }

    private Date getDataVencimento(){
        Date result = System.today();

        return result;
    }
}